pip install numpy
pip install numpy-financial
pip install pint
pip install forex_python
pip install jsons
pip install json
pip install pprint
pip install mpmath
pip install deepdiff
pip install functools
pip install mysql.connector
pip install hashlib
pip install h5py
pip install scipy
pip install itertools
